id: I9B66392B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T18:21:51+00:00'
last_modified: '2022-06-08T01:53:14.493313+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG17054
  title: ཞང་ཞུང་གི་ལྡེབས་རིས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    E81E:
      image_group_id: I1KG17078
      title: ''
      total_pages: 168
      order: 1
      base_file: E81E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
